'use client';

import { IdTokenResult, User } from 'firebase/auth';
import { Task, Goal } from '../types/common';

export const PRIORITY_VALUES = [
  { background: 'bg-red-800', text: 'text-white', value: 'High' },
  { background: 'bg-yellow-500', text: 'text-black', value: 'Medium' },
  { background: 'bg-green-500', text: 'text-black', value: 'Low' },
];

// TODO: Use later
// eslint-disable-next-line import/prefer-default-export
export const dummyUser: User = {
  displayName: "Mike O'Hearn",
  emailVerified: true,
  email: 'mikeyohearn@gmail.com',
  phoneNumber: '+1-202-555-0131',
  refreshToken: 'refresh-token',
  isAnonymous: false,
  metadata: {},
  providerData: [],
  tenantId: null,
  delete(): Promise<void> {
    throw new Error('Function not implemented.');
  },
  // eslint-disable-next-line no-unused-vars, @typescript-eslint/no-unused-vars
  getIdToken(forceRefresh?: boolean | undefined): Promise<string> {
    throw new Error('Function not implemented.');
  },
  getIdTokenResult(
    // eslint-disable-next-line no-unused-vars, @typescript-eslint/no-unused-vars
    forceRefresh?: boolean | undefined
  ): Promise<IdTokenResult> {
    throw new Error('Function not implemented.');
  },
  reload(): Promise<void> {
    throw new Error('Function not implemented.');
  },
  toJSON(): object {
    throw new Error('Function not implemented.');
  },
  photoURL:
    'https://cdn.shopify.com/s/files/1/1957/2713/files/tile-partner-mike-titan-ohearn_150x.png?v=1655998083',
  providerId: 'some-provider-id',
  uid: 'some-uid',
};

export const taskData: Task[] = [
  {
    id: '1',
    title: 'Run 5 miles',
    description: 'Go out to run 5 miles',
    parentId: '3',
    priority: 2,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    title: 'Clean 10 dishes',
    description: 'Clean 10 dishes',
    parentId: '4',
    priority: 3,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'Read a book',
    description: 'Read 15 pages',
    parentId: '1',
    priority: 2,
    hoursRequired: 3,
    status: 'DONE',
    dateAndTime: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    title: 'Meditate',
    description: 'Meditate for 10 minutes',
    parentId: '5',
    priority: 3,
    hoursRequired: 3,
    status: 'DONE',
    dateAndTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    title: 'Do the laundry',
    description: 'Do the laundry',
    parentId: '2',
    priority: 1,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    title: 'Grocery shopping',
    description: 'Buy groceries for the week',
    parentId: '2',
    priority: 2,
    hoursRequired: 2,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    title: 'Call family',
    description: 'Catch up with family over a phone call',
    parentId: '3',
    priority: 1,
    hoursRequired: 1,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8',
    title: 'Read a book',
    description: 'Read 15 pages',
    parentId: '1',
    priority: 2,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '9',
    title: 'Meditate',
    description: 'Meditate for 10 minutes',
    parentId: '5',
    priority: 3,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now()).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '10',
    title: 'Clean 10 dishes',
    description: 'Clean 10 dishes',
    parentId: '4',
    priority: 3,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '11',
    title: 'Do the laundry',
    description: 'Do the laundry',
    parentId: '2',
    priority: 1,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '12',
    title: 'Read a book',
    description: 'Read 15 pages',
    parentId: '1',
    priority: 2,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '13',
    title: 'Grocery shopping',
    description: 'Buy groceries for the week',
    parentId: '2',
    priority: 2,
    hoursRequired: 2,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '14',
    title: 'Call family',
    description: 'Catch up with family over a phone call',
    parentId: '3',
    priority: 1,
    hoursRequired: 1,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '15',
    title: 'Meditate',
    description: 'Meditate for 10 minutes',
    parentId: '5',
    priority: 3,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '16',
    title: 'Read a book',
    description: 'Read 15 pages',
    parentId: '1',
    priority: 2,
    hoursRequired: 3,
    status: 'DONE',
    dateAndTime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '17',
    title: 'Clean 10 dishes',
    description: 'Clean 10 dishes',
    parentId: '4',
    priority: 3,
    hoursRequired: 3,
    status: 'DONE',
    dateAndTime: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '18',
    title: 'Do the laundry',
    description: 'Do the laundry',
    parentId: '2',
    priority: 1,
    hoursRequired: 3,
    status: 'DONE',
    dateAndTime: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '19',
    title: 'Grocery shopping',
    description: 'Buy groceries for the week',
    parentId: '2',
    priority: 2,
    hoursRequired: 2,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '20',
    title: 'Call family',
    description: 'Catch up with family over a phone call',
    parentId: '3',
    priority: 1,
    hoursRequired: 1,
    status: 'DONE',
    dateAndTime: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '21',
    title: 'Meditate',
    description: 'Meditate for 10 minutes',
    parentId: '5',
    priority: 3,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '22',
    title: 'Read a book',
    description: 'Read 15 pages',
    parentId: '1',
    priority: 2,
    hoursRequired: 3,
    status: 'DONE',
    dateAndTime: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '23',
    title: 'Clean 10 dishes',
    description: 'Clean 10 dishes',
    parentId: '4',
    priority: 3,
    hoursRequired: 3,
    status: 'NOT_STARTED',
    dateAndTime: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '24',
    title: 'Do the laundry',
    description: 'Do the laundry',
    parentId: '2',
    priority: 1,
    hoursRequired: 3,
    status: 'DONE',
    dateAndTime: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const goalData: Goal[] = [
  {
    id: '1',
    userId: 'user1',
    title: 'Run a Marathon',
    description: 'Train to complete a full marathon within the next 12 months.',
    bgImageUrl:
      'https://images.unsplash.com/photo-1524046026319-4a3bce40c999?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    overlayColor: '#FF4500', // Orange Red
    status: 'IN_PROGRESS',
    expectedCompletionDate: '2024-11-22',
    createdAt: '2023-11-22',
    updatedAt: '2023-11-22',
    currentHoursSpent: 20,
    expectedHours: 200,
  },
  {
    id: '2',
    userId: 'user2',
    title: 'Read 50 Books',
    description: 'Expand knowledge by reading 50 books over the next year.',
    bgImageUrl:
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    overlayColor: '#8A2BE2', // Blue Violet
    status: 'NOT_STARTED',
    expectedCompletionDate: '2025-01-01',
    createdAt: '2023-11-22',
    updatedAt: '2023-11-22',
    currentHoursSpent: 0,
    expectedHours: 400,
  },
  {
    id: '3',
    userId: 'user3',
    title: 'Master Meditation',
    description: 'Achieve advanced proficiency in meditation within 18 months.',
    bgImageUrl:
      'https://images.unsplash.com/photo-1529693662653-9d480530a697?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    overlayColor: '#FFD700', // Gold
    status: 'IN_PROGRESS',
    expectedCompletionDate: '2025-05-22',
    createdAt: '2023-11-01',
    updatedAt: '2023-11-20',
    currentHoursSpent: 100,
    expectedHours: 600,
  },
  {
    id: '4',
    userId: 'user4',
    title: 'Start a Vegetable Garden',
    description: 'Cultivate a home vegetable garden over the next 6 months.',
    bgImageUrl:
      'https://images.unsplash.com/photo-1516253593875-bd7ba052fbc5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    overlayColor: '#32CD32', // Lime Green
    status: 'NOT_STARTED',
    expectedCompletionDate: '2024-05-22',
    createdAt: '2023-11-15',
    updatedAt: '2023-11-20',
    currentHoursSpent: 0,
    expectedHours: 50,
  },
  {
    id: '5',
    userId: 'user5',
    title: 'Learn to Play the Guitar',
    description: 'Become proficient in playing the guitar within a year.',
    bgImageUrl:
      'https://images.unsplash.com/photo-1535587566541-97121a128dc5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    overlayColor: '#1E90FF', // Dodger Blue
    status: 'IN_PROGRESS',
    expectedCompletionDate: '2024-11-22',
    createdAt: '2023-06-01',
    updatedAt: '2023-11-21',
    currentHoursSpent: 150,
    expectedHours: 500,
  },
];
