FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.work go.work.sum ./
COPY pkg/ ./pkg/
COPY services/ ./services/
WORKDIR /app/services/tasks
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/server ./cmd/server/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/bin/server .
EXPOSE 9000
CMD ["./server"]
